// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetworkAnalytics.Services.Entities;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetworkAnalytics.Migrations
{
    [DbContext(typeof(ContextDB))]
    partial class ContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetworkAnalytics.Models.Database.CommonWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdReport")
                        .HasColumnType("integer");

                    b.Property<int>("NumberRepetitions")
                        .HasColumnType("integer");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CommonWord");
                });

            modelBuilder.Entity("NetworkAnalytics.Models.Database.PartsSpeech", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ADJ")
                        .HasColumnType("integer");

                    b.Property<int>("ADP")
                        .HasColumnType("integer");

                    b.Property<int>("ADV")
                        .HasColumnType("integer");

                    b.Property<int>("DET")
                        .HasColumnType("integer");

                    b.Property<int>("INTJ")
                        .HasColumnType("integer");

                    b.Property<int>("IdReport")
                        .HasColumnType("integer");

                    b.Property<int>("NOUN")
                        .HasColumnType("integer");

                    b.Property<int>("NUM")
                        .HasColumnType("integer");

                    b.Property<int>("PART")
                        .HasColumnType("integer");

                    b.Property<int>("PRON")
                        .HasColumnType("integer");

                    b.Property<int>("SYM")
                        .HasColumnType("integer");

                    b.Property<int>("VERB")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PartsSpeech");
                });

            modelBuilder.Entity("NetworkAnalytics.Models.Database.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountMessages")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreateDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dialog")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SocialNetwork")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("NetworkAnalytics.Models.Database.TelegramUser", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<byte[]>("Icon")
                        .HasColumnType("bytea");

                    b.Property<int?>("IdUser")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("NameSession")
                        .HasColumnType("text");

                    b.Property<string>("NickName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TelegramUser");
                });

            modelBuilder.Entity("NetworkAnalytics.Models.Database.Them", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Art")
                        .HasColumnType("real");

                    b.Property<int>("IdReport")
                        .HasColumnType("integer");

                    b.Property<float>("Politics")
                        .HasColumnType("real");

                    b.Property<float>("Sport")
                        .HasColumnType("real");

                    b.Property<float>("Technic")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Them");
                });

            modelBuilder.Entity("NetworkAnalytics.Models.Database.Tonality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdReport")
                        .HasColumnType("integer");

                    b.Property<float>("Median")
                        .HasColumnType("real");

                    b.Property<float>("Negative")
                        .HasColumnType("real");

                    b.Property<float>("Positive")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Tonality");
                });

            modelBuilder.Entity("NetworkAnalytics.Models.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("NetworkAnalytics.Models.Database.VKUser", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<byte[]>("Icon")
                        .HasColumnType("bytea");

                    b.Property<int?>("IdUser")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("NickName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("VkToken")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VkUser");
                });
#pragma warning restore 612, 618
        }
    }
}
